"""Single idempotent ContextCord round-closeout facade."""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from .config import HarnessConfig
from .identity import source_identity
from .memory import add_note
from .store import StateStore
from .util import absolute_path, atomic_write_json, canonical_json, utc_now


SCHEMA = "contextcord-closeout-receipt-v1"


def _digest(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def _load_summary(path: Path | None, text: str | None, *, task_id: str | None, session_id: str | None) -> dict[str, Any]:
    if path:
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise ValueError("closeout_summary_must_be_object")
    else:
        value = {"summary": text or "ContextCord round closeout", "changes": [], "decisions": [], "unresolved": [], "next_steps": []}
    value.setdefault("task_id", task_id)
    value.setdefault("session_id", session_id)
    for key in ("changes", "decisions", "unresolved", "next_steps"):
        if not isinstance(value.get(key, []), list) or not all(isinstance(item, str) for item in value.get(key, [])):
            raise ValueError(f"closeout_{key}_must_be_string_array")
    return value


def _write_generated_doc(repo: Path, round_id: str, summary: dict[str, Any], source_sha: str) -> Path:
    target = repo / "docs" / "generated" / "contextcord-closeout" / f"{round_id}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# {round_id}", "", "> Generated by the ContextCord closeout facade. This is not a completion claim.", ""]
    if summary.get("summary"):
        lines += ["## Summary", "", str(summary["summary"]), ""]
    for key in ("changes", "decisions", "unresolved", "next_steps"):
        lines += [f"## {key.replace('_', ' ').title()}", ""]
        lines += [f"- {item}" for item in summary.get(key, [])] or ["- None recorded."]
        lines.append("")
    lines += ["## Source binding", "", f"- Source identity: `{source_sha}`", "- Publication: `NOT_REQUESTED`", ""]
    fd, temp_name = tempfile.mkstemp(prefix=".contextcord-closeout-", dir=str(target.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("\n".join(lines))
        os.replace(temp_name, target)
    finally:
        Path(temp_name).unlink(missing_ok=True)
    return target


def _architecture_phase(repo: Path, mode: str) -> dict[str, Any]:
    """Run the repository's single architecture sync entry point.

    The helper is intentionally best-effort for ordinary private closeout:
    missing Node/Archify reports ``RENDER_PENDING`` and never becomes a false
    sync claim.  The release drift gate remains the strict authority.
    """
    if mode == "never":
        return {"status": "NOT_REQUESTED", "mode": mode}
    script = Path(__file__).resolve().parents[2] / "scripts" / "architecture_sync.py"
    if not script.is_file():
        return {"status": "RENDER_PENDING", "mode": mode, "reason": "architecture_sync_script_unavailable"}
    try:
        result = subprocess.run(
            [sys.executable, str(script), "auto", "--repo", str(repo)],
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    except OSError as exc:
        return {"status": "RENDER_PENDING", "mode": mode, "reason": f"architecture_sync_launch_failed:{exc}"}
    candidates = [result.stdout.strip(), *reversed([line.strip() for line in result.stdout.splitlines() if line.strip()])]
    for line in candidates:
        if not line:
            continue
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            value.setdefault("mode", mode)
            return value
    return {
        "status": "RENDER_PENDING" if result.returncode == 0 else "VALIDATION_FAILED",
        "mode": mode,
        "reason": (result.stderr or result.stdout)[-2000:] or "architecture_sync_no_json_output",
    }


def closeout(
    cfg: HarnessConfig,
    *,
    summary_path: Path | None = None,
    summary_text: str | None = None,
    task_id: str | None = None,
    session_id: str | None = None,
    update_memory: bool = False,
    update_docs: bool = False,
    architecture: str = "if-changed",
) -> dict[str, Any]:
    repo = absolute_path(cfg.repo)
    with StateStore(repo) as store:
        if task_id is None:
            active = store.active_tasks()
            if len(active) == 1:
                task_id = str(active[0]["task_id"])
        if task_id is None:
            return {"schema": SCHEMA, "status": "BLOCKED", "reason": "task_id_required_or_unambiguous_active_task"}
        task = store.get_task(task_id)
        if task is None:
            return {"schema": SCHEMA, "status": "BLOCKED", "reason": "unknown_task", "task_id": task_id}
        if session_id is None:
            sessions = store.sessions_for_task(task_id)
            open_sessions = [row for row in sessions if row.get("status") == "OPEN"]
            if len(open_sessions) == 1:
                session_id = str(open_sessions[0]["session_id"])
        summary = _load_summary(summary_path, summary_text, task_id=task_id, session_id=session_id)
        identity = source_identity(cfg)
        source_sha = str(identity["identity_sha256"])
        key = _digest({"task_id": task_id, "session_id": session_id, "summary": summary, "source": source_sha})
    closeout_root = cfg.root / "closeout"
    receipt_path = closeout_root / f"{key}.json"
    if receipt_path.is_file():
        old = json.loads(receipt_path.read_text(encoding="utf-8"))
        return {**old, "status": "NOOP", "idempotent": True}
    closeout_root.mkdir(parents=True, exist_ok=True)
    lock = closeout_root / "running.lock"
    try:
        fd = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        os.close(fd)
    except FileExistsError:
        return {"schema": SCHEMA, "status": "LOCKED", "reason": "closeout_in_progress"}
    try:
        if receipt_path.is_file():
            old = json.loads(receipt_path.read_text(encoding="utf-8"))
            return {**old, "status": "NOOP", "idempotent": True}
        phase_receipts: list[dict[str, Any]] = [{"phase": "source_identity", "status": "PASS", "identity_sha256": source_sha}]
        with StateStore(repo) as store:
            evidence = store.evidence_for_task(task_id)
            phase_receipts.append({"phase": "tests_evidence", "status": "PASS" if evidence else "NOT_EVALUATED", "count": len(evidence)})
            sessions = store.sessions_for_task(task_id)
            phase_receipts.append({"phase": "task_session_handoff", "status": "PASS" if sessions else "NOT_EVALUATED", "session_count": len(sessions)})
        memory_status = "NOT_REQUESTED"
        if update_memory:
            if not session_id:
                memory_status = "BLOCKED_NO_SESSION"
            else:
                note_id = "closeout-" + key[:24]
                note = add_note(cfg, task_id=task_id, session_id=session_id, note_id=note_id,
                                text="\n".join([str(summary.get("summary") or "closeout"), *[f"DECISION: {x}" for x in summary.get("decisions", [])], *[f"OPEN: {x}" for x in summary.get("unresolved", [])], *[f"NEXT: {x}" for x in summary.get("next_steps", [])]]))
                memory_status = "RECORDED" if note.get("note_id") else "FAILED"
        phase_receipts.append({"phase": "durable_notes", "status": memory_status})
        docs_status = "NOT_REQUESTED"
        doc_path = None
        if update_docs:
            doc_path = _write_generated_doc(repo, str(summary.get("round_id") or key[:16]), summary, source_sha)
            docs_status = "RECORDED"
        phase_receipts.append({"phase": "docs_generated_zone", "status": docs_status, "path": str(doc_path.relative_to(repo)).replace("\\", "/") if doc_path else None})
        architecture_result = _architecture_phase(repo, architecture)
        arch_status = str(architecture_result.get("status") or "RENDER_PENDING")
        phase_receipts.append({"phase": "architecture", "status": arch_status, "result": architecture_result})
        release_status = "CANDIDATE_ONLY"
        phase_receipts.append({"phase": "release_readiness_candidate", "status": release_status})
        receipt = {
            "schema": SCHEMA,
            "status": "RECORDED",
            "idempotent": False,
            "recorded_at": utc_now(),
            "task_id": task_id,
            "session_id": session_id,
            "summary": summary,
            "source_identity_sha256": source_sha,
            "phase_receipts": phase_receipts,
            "memory_status": memory_status,
            "docs_status": docs_status,
            "architecture_status": arch_status,
            "release_status": release_status,
            "publication": "NOT_REQUESTED",
        }
        atomic_write_json(receipt_path, receipt)
        return receipt
    finally:
        lock.unlink(missing_ok=True)
