window.CONTEXTCORD_I18N = {
  en: {
    common: {
      home: "Home", docs: "Docs", integrations: "Integrations", research: "Research", readme: "README", language: "中文", theme: "Toggle theme", footer: "Portable engineering continuity for coding agents. Local-first, evidence-aware and vendor-neutral.", alpha: "Public Alpha", localBoundary: "Local state, host permissions and OS isolation remain authoritative."
    },
    docs: {
      eyebrow: "Product documentation", title: "Continue engineering work with a bounded, portable context.", lead: "ContextCord keeps the work state that matters at session boundaries: task intent, decisions, provenance, freshness and recoverable evidence.", start: "Start locally", startText: "Install the package in an isolated environment, initialize a local profile, then inspect the host-neutral health report.", boundaryTitle: "A clear local data boundary", boundaryText: "Your project state and archives remain local. A host receives only the context packet you choose to expose for a continuation. Integrity, secrets, permissions and release gates stay code-owned.", workflowTitle: "A continuation has four deliberate steps", workflowText: "The lifecycle is the same whether the next session runs in an IDE, a CLI, a team host or a BYOH adapter.", step1: "Capture", step1Text: "Bind the task, session, source identity, decisions and evidence.", step2: "Revalidate", step2Text: "Mark stale or conflicting context before it can silently steer work.", step3: "Select", step3Text: "Choose only relevant records within a bounded token budget.", step4: "Resume", step4Text: "Give the next host a final packet and open a new session.", nextTitle: "Continue with the public guides", quick: "Quickstart", architecture: "Architecture", integrationGuide: "Host integrations", researchGuide: "Research boundaries", readmeLink: "Repository README"
    },
    integrations: {
      eyebrow: "Host integrations", title: "Use the host you already trust.", lead: "The five first-class hosts have equal product status. Their native configuration contracts stay in adapters; policy and evidence remain vendor-neutral.", builtIn: "Built-in hosts", host: "Host", projectConfig: "Project configuration", verify: "Verification", status: "Adapter status", codexPath: "Project ~/.codex/config.toml or .codex/config.toml", codexVerify: "codex mcp list", qoderPath: "Project .mcp.json or Qoder settings", qoderVerify: "qoder mcp list or /mcp reload", cursorPath: "Project .cursor/mcp.json or global Cursor MCP settings", cursorVerify: "Cursor MCP panel or cursor-agent mcp list", opencodePath: "Project opencode.json or opencode.jsonc", opencodeVerify: "opencode mcp list", workbuddyPath: "Project .mcp.json or ~/.codebuddy/.mcp.json", workbuddyVerify: "codebuddy mcp list", pass: "PASS", byohTitle: "Bring your own host", byohText: "Other hosts use the Adapter Manifest contract. They can translate their native MCP configuration without copying policy decisions into the adapter.", byohSchema: "contextcord-host-adapter-v1", example: "Minimal stdio entry", notes: "The snippets below show the public shape. Replace the command with the installed CLI path when your host requires it.", fairness: "Equal host tier does not mean equal benchmark evidence: product integration, native continuation, and current live qualification are separate registry dimensions."
    },
    research: {
      eyebrow: "Research and evidence", title: "See what informed a route, what actually ran, and what the verifier learned.", lead: "ContextCord keeps model intelligence, routing decisions, and verified local outcomes as separate evidence layers instead of collapsing them into one score.", contextTitle: "Model intelligence prior", contextText: "Optional external benchmark data can shape the analysis shortlist. It is an advisory prior, not proof that a route is executable in the current host.", liveTitle: "Local Outcome Ledger", liveText: "A route enters local outcomes only after a real host execution and verifier result. Model, reasoning effort, latency, tokens, and observed cost remain distinct observations.", boundaryTitle: "Decision receipt", boundaryText: "Planner recommendation, optional Jev semantic Choice, effective route, and verifier outcome are recorded separately. Code still owns eligibility, permissions, budgets, and execution.", statusTitle: "Current research evidence", statusLoading: "Load the staged research summary", statusFallback: "No current public summary has been staged yet; the product remains usable without research data.", limitations: "Known limits", limitation1: "Model identity and usage are recorded only when the host exposes them.", limitation2: "External benchmark cost is an analysis signal, not a claim about subscription quota consumed by a host.", limitation3: "A local outcome applies to the observed project, task profile, and verifier boundary; it does not qualify every future build.", registry: "Host Evidence Registry v3", registryText: "The ContextCord-native registry separates integration, continuation evidence, and current qualification for Codex, Qoder, Cursor, OpenCode, and WorkBuddy.", benchmarkFiles: "Router and outcome records", contextFile: "Model intelligence records", sourceNote: "Public staging excludes raw provider payloads, private archives, local state databases, and internal progress logs."
    },
    workbench: {
      eyebrow: "Local workbench", title: "A calm surface for the next continuation.", lead: "The public workbench is intentionally small: inspect the task, choose the evidence boundary, and let the host do the implementation inside its own workspace.", card1: "Task state", card1Text: "Keep intent, next action and current source identity together.", card2: "Evidence", card2Text: "Separate current facts, stale notes and restorable archives.", card3: "Host session", card3Text: "Create a bounded packet for Codex, Qoder, Cursor, OpenCode, WorkBuddy or a BYOH adapter.", openDocs: "Read the docs", openResearch: "See the evidence boundary", note: "This page is a public product surface, not a live view into your private project state."
    }
  },
  zh: {
    common: {
      home: "首页", docs: "文档", integrations: "集成", research: "研究", readme: "README", language: "EN", theme: "切换主题", footer: "面向 Coding Agent 的可移植工程连续性基础设施。本地优先、证据感知、厂商中立。", alpha: "Public Alpha"
    },
    docs: {
      eyebrow: "产品文档", title: "用有边界、可移植的上下文继续工程工作。", lead: "ContextCord 在会话边界保存真正影响继续开发的状态：任务意图、决策、来源、新鲜度与可恢复证据。", start: "本地开始", startText: "在隔离环境安装包，初始化本地 profile，然后查看与宿主无关的健康报告。", boundaryTitle: "清晰的本地数据边界", boundaryText: "你的工程状态与 Archive 保留在本地。宿主只会收到你选择暴露给下一次接续的 context packet。完整性、密钥、权限与发布 gate 继续由代码掌控。", workflowTitle: "一次接续包含四个明确步骤", workflowText: "无论下一次会话运行在 IDE、CLI、团队宿主还是 BYOH adapter 中，生命周期都保持一致。", step1: "记录", step1Text: "绑定任务、会话、源码身份、决策与证据。", step2: "重检", step2Text: "在旧上下文静默影响工作之前，标记过期或冲突内容。", step3: "选择", step3Text: "在有界 token 预算内只选择相关记录。", step4: "继续", step4Text: "把最终 packet 交给下一宿主并创建新会话。", nextTitle: "继续阅读公开指南", quick: "快速开始", architecture: "架构", integrationGuide: "宿主集成", researchGuide: "研究边界", readmeLink: "仓库 README"
    },
    integrations: {
      eyebrow: "宿主集成", title: "使用你已经信任的宿主。", lead: "五个一级宿主拥有相同的产品地位。它们的原生配置合同留在 adapter 中；策略与证据保持厂商中立。", builtIn: "一级 built-in 宿主", host: "宿主", projectConfig: "项目配置", verify: "验证", status: "Adapter 状态", codexPath: "项目 ~/.codex/config.toml 或 .codex/config.toml", codexVerify: "codex mcp list", qoderPath: "项目 .mcp.json 或 Qoder settings", qoderVerify: "qoder mcp list 或 /mcp reload", cursorPath: "项目 .cursor/mcp.json 或 Cursor 全局 MCP settings", cursorVerify: "Cursor MCP 面板或 cursor-agent mcp list", opencodePath: "项目 opencode.json 或 opencode.jsonc", opencodeVerify: "opencode mcp list", workbuddyPath: "项目 .mcp.json 或 ~/.codebuddy/.mcp.json", workbuddyVerify: "codebuddy mcp list", pass: "PASS", byohTitle: "接入自己的宿主", byohText: "其它宿主使用 Adapter Manifest 合同。它们可以翻译自己的 MCP 配置，但不能把策略决策复制进 adapter。", byohSchema: "contextcord-host-adapter-v1", example: "最小 stdio 配置", notes: "下面的片段展示公开配置形状。宿主需要时，请将 command 替换为本机 CLI 路径。", fairness: "一级宿主不等于拥有相同 benchmark 证据：产品集成、原生连续性和当前 live qualification 在 Registry 中是三个独立维度。"
    },
    research: {
      eyebrow: "研究与证据", title: "看清路线依据、真实执行，以及 verifier 最终学到了什么。", lead: "ContextCord 将模型智能、路由决策和经过验证的本地 Outcome 分成独立证据层，而不是压成一个看似简单的总分。", contextTitle: "Model Intelligence 先验", contextText: "可选的外部 benchmark 数据可以影响 analysis shortlist。它只是 advisory prior，不证明当前宿主一定能够执行某条路线。", liveTitle: "Local Outcome Ledger", liveText: "只有真实宿主执行并得到 verifier 结果后，路线才进入本地 Outcome。Model、reasoning effort、延迟、token 与实际观测成本保持为独立字段。", boundaryTitle: "Decision Receipt", boundaryText: "Planner recommendation、可选 Jev semantic Choice、effective route 与 verifier outcome 分层记录。资格、权限、预算与执行仍由代码掌控。", statusTitle: "当前研究证据", statusLoading: "加载已 staged 的研究 summary", statusFallback: "当前没有 staged 公开 summary；研究数据缺失不会影响核心产品使用。", limitations: "已知限制", limitation1: "只有宿主明确暴露时，才会记录 model identity 与 usage。", limitation2: "外部 benchmark 成本是分析信号，不等同于宿主订阅额度的实际消耗。", limitation3: "Local Outcome 只适用于被观察到的项目、任务 profile 与 verifier 边界，不能替未来每个 build 自动 qualification。", registry: "Host Evidence Registry v3", registryText: "ContextCord-native Registry 将 Codex、Qoder、Cursor、OpenCode、WorkBuddy 的 integration、continuation 证据和当前 qualification 分成独立维度。", benchmarkFiles: "Router 与 Outcome 记录", contextFile: "Model Intelligence 记录", sourceNote: "公开 staging 会排除 provider raw payload、私有 Archive、本地 state database 与内部进度日志。"
    },
    workbench: {
      eyebrow: "本地 workbench", title: "为下一次接续保留一块安静的工作面。", lead: "公开 workbench 有意保持轻量：查看任务、选择证据边界，然后让宿主在自己的 workspace 内完成实现。", card1: "任务状态", card1Text: "把意图、下一步和当前源码身份放在一起。", card2: "证据", card2Text: "区分当前事实、过期笔记和可恢复 Archive。", card3: "宿主会话", card3Text: "为 Codex、Qoder、Cursor、OpenCode、WorkBuddy 或 BYOH adapter 创建有界 packet。", openDocs: "阅读文档", openResearch: "查看证据边界", note: "这是公开产品页面，不是你私有工程状态的实时视图。"
    }
  }
};
